// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCL21V0B1i9bzi0HBa5fqa1r9ejOY1RAqA',
//     appId: '1:496961273230:android:8e680b55948554773a78df',
//     messagingSenderId: '496961273230',
//     projectId: 'my-qurbaani',
//     authDomain: 'flutterptactice.firebaseapp.com',
//     storageBucket: 'flutterptactice.appspot.com',
//     measurementId: 'G-WPV0BLSFC2',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCmmREb1rWwW1skle-E9yeVm7HpIPGaA9o',
//     appId: '1:496961273230:android:8e680b55948554773a78df',
//     messagingSenderId: '496961273230',
//     projectId: 'my-qurbaani',
//     storageBucket: 'flutterptactice.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyADc8qLLlB1_DFmrrX7CzjPScU4iK_qcY8',
//     appId: '1:496961273230:android:8e680b55948554773a78df',
//     messagingSenderId: '496961273230',
//     projectId: 'my-qurbaani',
//     storageBucket: 'flutterptactice.appspot.com',
//     iosClientId: '627042081484-3matv6t2vs70t0unpej75lbnb301gqok.apps.googleusercontent.com',
//     iosBundleId: 'com.alrighttech.my.qurbaani',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyADc8qLLlB1_DFmrrX7CzjPScU4iK_qcY8',
//     appId: '1:496961273230:android:8e680b55948554773a78df',
//     messagingSenderId: '496961273230',
//     projectId: 'my-qurbaani',
//     storageBucket: 'flutterptactice.appspot.com',
//     iosClientId: '627042081484-0qspcotj37cl4ido0o8et43gts2j4vcb.apps.googleusercontent.com',
//     iosBundleId: 'com.alrighttech.my.qurbaani',
//   );
// }
