// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6N7XM-jFhnIQBealrwdG1m72GvO_wN5o',
    appId: '1:659133084924:web:c364c6559dbb8751e2d379',
    messagingSenderId: '659133084924',
    projectId: 'healthpro-79ce3',
    authDomain: 'healthpro-79ce3.firebaseapp.com',
    storageBucket: 'healthpro-79ce3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLMeqdVsZGqQT6AfucRcBheqJkbLpvqzs',
    appId: '1:659133084924:android:ea3c94af4a96a86be2d379',
    messagingSenderId: '659133084924',
    projectId: 'healthpro-79ce3',
    storageBucket: 'healthpro-79ce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA61CRz2sp0DDDamW8kPor7hWre0eq65yM',
    appId: '1:659133084924:ios:1fc7664ac95061cae2d379',
    messagingSenderId: '659133084924',
    projectId: 'healthpro-79ce3',
    storageBucket: 'healthpro-79ce3.appspot.com',
    iosBundleId: 'com.example.healthPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA61CRz2sp0DDDamW8kPor7hWre0eq65yM',
    appId: '1:659133084924:ios:99e842e86080b97be2d379',
    messagingSenderId: '659133084924',
    projectId: 'healthpro-79ce3',
    storageBucket: 'healthpro-79ce3.appspot.com',
    iosBundleId: 'com.example.healthPro.RunnerTests',
  );
}
